### ISSUE TITLE
Download data location

### ISSUE THREAD

**Issue by cmfield** [ialbert/bio#23]
Hi,

I have made your neat tool available on our software module system, however, I wondered if there was a way to point the program at a centrally downloaded set of data (the data procured by --download), rather than each user downloading it themselves?

Thanks!

**Comment by ialbert** [comment]
I will add the ability to allow overriding the default location (currently set to `~/.bio`)

Currently, the simplest workaround would be to link another, already prepopulated directory as `.bio` in the home directory and that would suffice

for example: 

    # Moving working .bio directory to a public location
    mv ~/.bio  /export/public/bio
   
    # Change access right to files (if those are not set correctly)
    chmod -R 755  /export/public/bio
   
    # Each user can then link the public directory as local ~/.bio
    ln -s /export/public/bio  ~/.bio

**Comment by ialbert** [comment]
you can now set the BIO_DIR environment variable to customize the location of the data directory

    export BIO_DIR=/path/goes/here

included version 1.3.4

**Comment by cmfield** [comment]
Amazing, thanks so much!
