### ISSUE TITLE
invalid command: fasta2vcf

### ISSUE THREAD

**Issue by gyebra-phs** [ialbert/bio#27]
Hi! 

I wanted to use the `fasta2vcf` option of `bio` following the instructions in https://www.bioinfo.help/bio-fasta2vcf.html#bio-fasta2vcf

However, I get the following error: `invalid command: fasta2vcf`.

I'm using version 1.4.0 of `bio`. Any help would be appreciated!

Thanks

**Comment by ialbert** [comment]
sorry about that, need to update the docs; the command has been moved to `format`

    bio format --vcf

so the example becomes:

    cat aligned.fa | bio format --vcf  > variants.vcf

**Comment by ialbert** [comment]
the format also a supports  a simplified column-based format called `--diff` that is more amenable to column based operations

**Comment by gyebra-phs** [comment]
That’s great, thanks for your quick reply! I'll try that.

Gonzalo Yebra (he / him)
Bioinformatician
Public Health Microbiology
Public Health Scotland
________________________________
